/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Login;
import java.sql.*;
import Gimnasio.ConexionLocal;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.WindowConstants;

/**
 *
 * @author Deybi
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    
    
    String user , nombre_usuario;
    public static int sesion_usuario;
    
    public Administrador() {
        initComponents();
        user=LogIn.user;
        sesion_usuario = 1;
        
        setSize(650,430);
        setResizable(false);
        
        setTitle("Administrador");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        
        
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_FondoAdministrador, "E:\\7to ciclo\\Java\\JavaApplication2\\Proyecto_Gimnasio\\src\\Imagenes\\fondo.jpg");
        this.repaint();
        try {
            Connection cn = ConexionLocal.Conexion();
            PreparedStatement pst = cn.prepareStatement("Select usu_nombre from tbl_usuario where usu_login = '"+ user + "'");
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("usu_nombre");
                lbl_UsuAdmin.setText(nombre_usuario);
                
            }
            
            
        } catch (Exception e) { 
            System.err.println("Error en la interfaz deAdministrador");
        }
    
    }
    
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_UsuAdmin = new javax.swing.JLabel();
        btn_RegistrarUsuario = new javax.swing.JButton();
        btn_RevisarUsuario = new javax.swing.JButton();
        btn_RevisarCliente = new javax.swing.JButton();
        btn_AddMembership = new javax.swing.JButton();
        btn_RegistrarMembresia = new javax.swing.JButton();
        btn_RegistrarUsuario5 = new javax.swing.JButton();
        lbl_AddUser = new javax.swing.JLabel();
        lbl_ListaUsuario = new javax.swing.JLabel();
        lbl_ListaEmpleado = new javax.swing.JLabel();
        lbl_ListaMembresía = new javax.swing.JLabel();
        lbl_AñadirMembresía = new javax.swing.JLabel();
        lbl_AñadirMembresía1 = new javax.swing.JLabel();
        lbl_FondoAdministrador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_UsuAdmin.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lbl_UsuAdmin.setForeground(new java.awt.Color(255, 0, 0));
        lbl_UsuAdmin.setText("jLabel1");
        getContentPane().add(lbl_UsuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 50));

        btn_RegistrarUsuario.setIcon(new javax.swing.ImageIcon("E:\\7to ciclo\\Java\\JavaApplication2\\Imagenes\\896397_opt.png")); // NOI18N
        btn_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 130));

        btn_RevisarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_Cliente1_opt.png"))); // NOI18N
        btn_RevisarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RevisarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RevisarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 130, 130));

        btn_RevisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_cliente12_opt.png"))); // NOI18N
        btn_RevisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RevisarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RevisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, 130));

        btn_AddMembership.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_AddMembresía.png"))); // NOI18N
        btn_AddMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddMembershipActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AddMembership, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 130));

        btn_RegistrarMembresia.setIcon(new javax.swing.ImageIcon("E:\\7to ciclo\\Java\\JavaApplication2\\Imagenes\\btn_AddMembership.png")); // NOI18N
        btn_RegistrarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarMembresiaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 130, 130));

        btn_RegistrarUsuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/ingresos (1).png"))); // NOI18N
        btn_RegistrarUsuario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuario5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarUsuario5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 130, 130));

        lbl_AddUser.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_AddUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AddUser.setText("Añadir Usuario");
        getContentPane().add(lbl_AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 25));

        lbl_ListaUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaUsuario.setText("Lista de Usuarios");
        getContentPane().add(lbl_ListaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, 25));

        lbl_ListaEmpleado.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaEmpleado.setText("Lista de Clientes");
        getContentPane().add(lbl_ListaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 130, 25));

        lbl_ListaMembresía.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaMembresía.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaMembresía.setText("Lista de Membresía");
        getContentPane().add(lbl_ListaMembresía, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 25));

        lbl_AñadirMembresía.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_AñadirMembresía.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AñadirMembresía.setText("Añadir Membresía");
        getContentPane().add(lbl_AñadirMembresía, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, 25));

        lbl_AñadirMembresía1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_AñadirMembresía1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AñadirMembresía1.setText("Ingresos/Egresos");
        getContentPane().add(lbl_AñadirMembresía1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 130, 25));
        getContentPane().add(lbl_FondoAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuarioActionPerformed
        RegistrarUsuario registrarUsuario = new RegistrarUsuario();
        registrarUsuario.setVisible(true);
    }//GEN-LAST:event_btn_RegistrarUsuarioActionPerformed

    private void btn_RevisarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RevisarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RevisarUsuarioActionPerformed

    private void btn_RevisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RevisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RevisarClienteActionPerformed

    private void btn_AddMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddMembershipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AddMembershipActionPerformed

    private void btn_RegistrarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegistrarMembresiaActionPerformed

    private void btn_RegistrarUsuario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuario5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_RegistrarUsuario5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddMembership;
    private javax.swing.JButton btn_RegistrarMembresia;
    private javax.swing.JButton btn_RegistrarUsuario;
    private javax.swing.JButton btn_RegistrarUsuario5;
    private javax.swing.JButton btn_RevisarCliente;
    private javax.swing.JButton btn_RevisarUsuario;
    private javax.swing.JLabel lbl_AddUser;
    private javax.swing.JLabel lbl_AñadirMembresía;
    private javax.swing.JLabel lbl_AñadirMembresía1;
    private javax.swing.JLabel lbl_FondoAdministrador;
    private javax.swing.JLabel lbl_ListaEmpleado;
    private javax.swing.JLabel lbl_ListaMembresía;
    private javax.swing.JLabel lbl_ListaUsuario;
    private javax.swing.JLabel lbl_UsuAdmin;
    // End of variables declaration//GEN-END:variables
}
