/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Login;

import Gimnasio.ConexionLocal;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.WindowConstants;

/**
 *
 * @author Deybi
 */
public class Recepcionista extends javax.swing.JFrame {

    String user , nombre_usuario;
    public static int sesion_usuario;
    
    public Recepcionista() {
        initComponents();
        user=LogIn.user;
        sesion_usuario = 1;
        
        setSize(650,430);
        setResizable(false);
        
        setTitle("Recepcionista");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_FondoRecepcionista, "E:\\7to ciclo\\Java\\JavaApplication2\\Proyecto_Gimnasio\\src\\Imagenes\\fondo.jpg");
        this.repaint();
        
        try {
            Connection cn = ConexionLocal.Conexion();
            PreparedStatement pst = cn.prepareStatement("Select usu_nombre from tbl_usuario where usu_login = '"+ user + "'");
            
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("usu_nombre");
                lbl_UsuRecepcionista.setText(nombre_usuario);
                
            }
            
            
        } catch (Exception e) { 
            System.err.println("Error en la interfaz deAdministrador");
        }   
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_RegistrarUsuario = new javax.swing.JButton();
        btn_AñadirCliente = new javax.swing.JButton();
        btn_ListaCliente = new javax.swing.JButton();
        btn_ListaMembresia = new javax.swing.JButton();
        btn_ListaUsuario = new javax.swing.JButton();
        lbl_AddUser = new javax.swing.JLabel();
        lbl_ListaUsuario = new javax.swing.JLabel();
        lbl_ListaEmpleado = new javax.swing.JLabel();
        lbl_ListaMembresía = new javax.swing.JLabel();
        lbl_UsuRecepcionista = new javax.swing.JLabel();
        lbl_AddCustomer = new javax.swing.JLabel();
        lbl_FondoRecepcionista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_RegistrarUsuario.setIcon(new javax.swing.ImageIcon("E:\\7to ciclo\\Java\\JavaApplication2\\Imagenes\\896397_opt.png")); // NOI18N
        btn_RegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_RegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 130, 130));

        btn_AñadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/add_customer_opt.png"))); // NOI18N
        btn_AñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AñadirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_AñadirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 130));

        btn_ListaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_cliente12_opt.png"))); // NOI18N
        btn_ListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ListaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 130, 130));

        btn_ListaMembresia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_AddMembresía.png"))); // NOI18N
        btn_ListaMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListaMembresiaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ListaMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, 130));

        btn_ListaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz_Login/btn_Cliente1_opt.png"))); // NOI18N
        btn_ListaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListaUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ListaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, 130));

        lbl_AddUser.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_AddUser.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AddUser.setText("Añadir Usuario");
        getContentPane().add(lbl_AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, 25));

        lbl_ListaUsuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaUsuario.setText("Lista de Clientes");
        getContentPane().add(lbl_ListaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 130, 25));

        lbl_ListaEmpleado.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaEmpleado.setText("Lista de Usuarios");
        getContentPane().add(lbl_ListaEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 130, 25));

        lbl_ListaMembresía.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_ListaMembresía.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ListaMembresía.setText("Lista de Membresía");
        getContentPane().add(lbl_ListaMembresía, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 25));

        lbl_UsuRecepcionista.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lbl_UsuRecepcionista.setForeground(new java.awt.Color(255, 0, 0));
        lbl_UsuRecepcionista.setText("jLabel1");
        getContentPane().add(lbl_UsuRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 50));

        lbl_AddCustomer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        lbl_AddCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lbl_AddCustomer.setText("Añadir Cliente");
        getContentPane().add(lbl_AddCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 25));
        getContentPane().add(lbl_FondoRecepcionista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarUsuarioActionPerformed
        RegistrarUsuario registrarUsuario = new RegistrarUsuario();
        registrarUsuario.setVisible(true);
    }//GEN-LAST:event_btn_RegistrarUsuarioActionPerformed

    private void btn_AñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AñadirClienteActionPerformed
        RegistrarCliente registrarCliente = new RegistrarCliente();
        registrarCliente.setVisible(true);
        
    }//GEN-LAST:event_btn_AñadirClienteActionPerformed

    private void btn_ListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ListaClienteActionPerformed

    private void btn_ListaMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListaMembresiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ListaMembresiaActionPerformed

    private void btn_ListaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ListaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AñadirCliente;
    private javax.swing.JButton btn_ListaCliente;
    private javax.swing.JButton btn_ListaMembresia;
    private javax.swing.JButton btn_ListaUsuario;
    private javax.swing.JButton btn_RegistrarUsuario;
    private javax.swing.JLabel lbl_AddCustomer;
    private javax.swing.JLabel lbl_AddUser;
    private javax.swing.JLabel lbl_FondoRecepcionista;
    private javax.swing.JLabel lbl_ListaEmpleado;
    private javax.swing.JLabel lbl_ListaMembresía;
    private javax.swing.JLabel lbl_ListaUsuario;
    private javax.swing.JLabel lbl_UsuRecepcionista;
    // End of variables declaration//GEN-END:variables
}
