/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz_Login;

import Gimnasio.ConexionLocal;
import Gimnasio.ValidacionLetra;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class RegistrarUsuario extends javax.swing.JFrame {

    String usuario;
    ValidacionLetra validarLetra =new ValidacionLetra();
    public RegistrarUsuario() {
        initComponents();
        usuario = LogIn.user;
        setTitle("Registro de Nuevo Usuario");
        setSize(630,380);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_FondoRegistrarUsuario, "E:\\7to ciclo\\Java\\JavaApplication2\\Proyecto_Gimnasio\\src\\Imagenes\\fondo.jpg");
        this.repaint();
        
        
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TituloRegistroUsuario = new javax.swing.JLabel();
        lbl_NombreNuevoUsuario = new javax.swing.JLabel();
        txt_NombreNuevoUsuario = new javax.swing.JTextField();
        lbl_ApellidoPaternoNuevoUsuario = new javax.swing.JLabel();
        txt_ApellidoPaternoNuevoUsuario = new javax.swing.JTextField();
        lbl_ApellidoMaternoNuevoUsuario = new javax.swing.JLabel();
        txt_ApellidoMaternoNuevoUsuario = new javax.swing.JTextField();
        lbl_LoginNuevoUsuario = new javax.swing.JLabel();
        txt_LoginNuevoUsuario = new javax.swing.JTextField();
        lbl_PasswordNuevoUsuario = new javax.swing.JLabel();
        txt_PasswordNuevoUsuario = new javax.swing.JPasswordField();
        lbl_CargoNuevoUsuario = new javax.swing.JLabel();
        cmb_CargoNuevoUsuario = new javax.swing.JComboBox<>();
        btn_AgregarNuevoUsuario = new javax.swing.JButton();
        btn_CancelarNuevoUsuario = new javax.swing.JButton();
        lbl_FondoRegistrarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_TituloRegistroUsuario.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        lbl_TituloRegistroUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_TituloRegistroUsuario.setText("Registro de Usuario");
        getContentPane().add(lbl_TituloRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 15, 230, -1));

        lbl_NombreNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_NombreNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_NombreNuevoUsuario.setText("Nombre:");
        getContentPane().add(lbl_NombreNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 30));

        txt_NombreNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_NombreNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NombreNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_NombreNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreNuevoUsuarioActionPerformed(evt);
            }
        });
        txt_NombreNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_NombreNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, 30));

        lbl_ApellidoPaternoNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ApellidoPaternoNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_ApellidoPaternoNuevoUsuario.setText("Apellido Paterno:");
        getContentPane().add(lbl_ApellidoPaternoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 140, -1, 30));

        txt_ApellidoPaternoNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ApellidoPaternoNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ApellidoPaternoNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ApellidoPaternoNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoPaternoNuevoUsuarioActionPerformed(evt);
            }
        });
        txt_ApellidoPaternoNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoPaternoNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ApellidoPaternoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 140, 130, 30));

        lbl_ApellidoMaternoNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ApellidoMaternoNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_ApellidoMaternoNuevoUsuario.setText("Apellido Materno:");
        getContentPane().add(lbl_ApellidoMaternoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        txt_ApellidoMaternoNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ApellidoMaternoNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ApellidoMaternoNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ApellidoMaternoNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoMaternoNuevoUsuarioActionPerformed(evt);
            }
        });
        txt_ApellidoMaternoNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoMaternoNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ApellidoMaternoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, 30));

        lbl_LoginNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_LoginNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_LoginNuevoUsuario.setText("Login:");
        getContentPane().add(lbl_LoginNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        txt_LoginNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_LoginNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_LoginNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_LoginNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_LoginNuevoUsuarioActionPerformed(evt);
            }
        });
        txt_LoginNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_LoginNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_LoginNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 30));

        lbl_PasswordNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_PasswordNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_PasswordNuevoUsuario.setText("Pasword:");
        getContentPane().add(lbl_PasswordNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        txt_PasswordNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_PasswordNuevoUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_PasswordNuevoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_PasswordNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PasswordNuevoUsuarioActionPerformed(evt);
            }
        });
        txt_PasswordNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_PasswordNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(txt_PasswordNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 80, 130, 30));

        lbl_CargoNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_CargoNuevoUsuario.setForeground(new java.awt.Color(255, 102, 0));
        lbl_CargoNuevoUsuario.setText("Cargo:");
        getContentPane().add(lbl_CargoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 200, -1, 30));

        cmb_CargoNuevoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Recepcionista" }));
        cmb_CargoNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CargoNuevoUsuarioActionPerformed(evt);
            }
        });
        cmb_CargoNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmb_CargoNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(cmb_CargoNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 200, 130, 30));

        btn_AgregarNuevoUsuario.setText("Agregar");
        btn_AgregarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarNuevoUsuarioActionPerformed(evt);
            }
        });
        btn_AgregarNuevoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_AgregarNuevoUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(btn_AgregarNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 160, 40));

        btn_CancelarNuevoUsuario.setText("Cancelar");
        btn_CancelarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarNuevoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CancelarNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 160, 40));
        getContentPane().add(lbl_FondoRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NombreNuevoUsuarioActionPerformed

    private void txt_ApellidoPaternoNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoPaternoNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoPaternoNuevoUsuarioActionPerformed

    private void txt_ApellidoMaternoNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMaternoNuevoUsuarioActionPerformed

    private void txt_LoginNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_LoginNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_LoginNuevoUsuarioActionPerformed

    private void txt_PasswordNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PasswordNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PasswordNuevoUsuarioActionPerformed

    private void cmb_CargoNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CargoNuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_CargoNuevoUsuarioActionPerformed

    private void btn_AgregarNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_AgregarNuevoUsuarioKeyTyped
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_btn_AgregarNuevoUsuarioKeyTyped

    private void btn_AgregarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarNuevoUsuarioActionPerformed
        int cargo,error=0;
        String nombre,apellidoPaterno,apellidoMaterno,username,password,cmb_cargo;
        nombre =txt_NombreNuevoUsuario.getText().trim();
        
        apellidoPaterno =txt_ApellidoPaternoNuevoUsuario.getText().trim();
        apellidoMaterno =txt_ApellidoMaternoNuevoUsuario.getText().trim();
        username =txt_LoginNuevoUsuario.getText().trim();
        password =txt_PasswordNuevoUsuario.getText().trim();
        cargo= cmb_CargoNuevoUsuario.getSelectedIndex()+1;
        
        
        if(nombre.equals("")){
            txt_NombreNuevoUsuario.setBackground(Color.RED);
            error++;      
        }
        if(apellidoPaterno.equals("")){
            txt_ApellidoPaternoNuevoUsuario.setBackground(Color.RED);
            error++;      
        }
        if(apellidoMaterno.equals("")){
            txt_ApellidoMaternoNuevoUsuario.setBackground(Color.RED);
            error++;      
        }
        if(username.equals("")){
            txt_LoginNuevoUsuario.setBackground(Color.RED);
            error++;      
        }
        if(password.equals("")){
            txt_PasswordNuevoUsuario.setBackground(Color.RED);
            error++;      
        }
        if (cargo==1) {
            cmb_cargo="Administrador";
        } else {
            cmb_cargo="Recepcionista";
        }
        
        
        try {
            Connection cn = ConexionLocal.Conexion();
            
            PreparedStatement pst = cn.prepareStatement("select usu_Login from tbl_Usuario where usu_Login = '"+username+"' ");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                txt_LoginNuevoUsuario.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Nombre de usuario ya registrado");
                txt_LoginNuevoUsuario.setText("");
                cn.close();
            } else {
                
                cn.close();
                if (error == 0) {
                    try {
                        try (Connection cn2 = ConexionLocal.Conexion()) {
                            PreparedStatement pst2 = cn2.prepareStatement
                                ("INSERT INTO tbl_usuario  VALUES (?,?,?,?,?,?,?,?)");
                            
                            pst2.setInt(1, 0);
                            pst2.setString(2, nombre);
                            pst2.setString(3, apellidoPaterno);
                            pst2.setString(4, apellidoMaterno);
                            pst2.setString(5, username);
                            pst2.setString(6, password);
                            pst2.setString(7, "Activo");
                            pst2.setString(8, cmb_cargo);
                            //pst2.setString(9, user);
                            
                            pst2.executeUpdate();
                        }
                        CamposVacios();
                        JOptionPane.showMessageDialog(null,"Registro Exitoso");
                        this.dispose();
                        
                        
                    } catch (SQLException e) {
                        System.err.println("No se pudo registrar al usuario"+ e);
                        JOptionPane.showMessageDialog(null,"Error al agregar usuario");
                        CamposVacios();
                        
                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Rellene todos los campos");
                    
                }
                
            }
        } catch (SQLException e) {
            System.err.println("No se puedo validar el nombre de usuario");
            JOptionPane.showMessageDialog(null,"Error en la Base de Datos"+ e);
        }
        
        
        
    }//GEN-LAST:event_btn_AgregarNuevoUsuarioActionPerformed

    private void btn_CancelarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarNuevoUsuarioActionPerformed
        CamposVacios();
        dispose();
    }//GEN-LAST:event_btn_CancelarNuevoUsuarioActionPerformed

    private void txt_NombreNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreNuevoUsuarioKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_txt_NombreNuevoUsuarioKeyTyped

    private void txt_LoginNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_LoginNuevoUsuarioKeyTyped
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_txt_LoginNuevoUsuarioKeyTyped

    private void txt_ApellidoPaternoNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoPaternoNuevoUsuarioKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_txt_ApellidoPaternoNuevoUsuarioKeyTyped

    private void txt_PasswordNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PasswordNuevoUsuarioKeyTyped
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_txt_PasswordNuevoUsuarioKeyTyped

    private void txt_ApellidoMaternoNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoNuevoUsuarioKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_txt_ApellidoMaternoNuevoUsuarioKeyTyped

    private void cmb_CargoNuevoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_CargoNuevoUsuarioKeyTyped
        char tecEnter= evt.getKeyChar();
        
        
        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AgregarNuevoUsuario.doClick();
        
        }
    }//GEN-LAST:event_cmb_CargoNuevoUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarNuevoUsuario;
    private javax.swing.JButton btn_CancelarNuevoUsuario;
    private javax.swing.JComboBox<String> cmb_CargoNuevoUsuario;
    private javax.swing.JLabel lbl_ApellidoMaternoNuevoUsuario;
    private javax.swing.JLabel lbl_ApellidoPaternoNuevoUsuario;
    private javax.swing.JLabel lbl_CargoNuevoUsuario;
    private javax.swing.JLabel lbl_FondoRegistrarUsuario;
    private javax.swing.JLabel lbl_LoginNuevoUsuario;
    private javax.swing.JLabel lbl_NombreNuevoUsuario;
    private javax.swing.JLabel lbl_PasswordNuevoUsuario;
    private javax.swing.JLabel lbl_TituloRegistroUsuario;
    private javax.swing.JTextField txt_ApellidoMaternoNuevoUsuario;
    private javax.swing.JTextField txt_ApellidoPaternoNuevoUsuario;
    private javax.swing.JTextField txt_LoginNuevoUsuario;
    private javax.swing.JTextField txt_NombreNuevoUsuario;
    private javax.swing.JPasswordField txt_PasswordNuevoUsuario;
    // End of variables declaration//GEN-END:variables

    public void CamposVacios(){
        txt_NombreNuevoUsuario.setText("");
        txt_ApellidoPaternoNuevoUsuario.setText("");
        txt_ApellidoMaternoNuevoUsuario.setText("");
        txt_LoginNuevoUsuario.setText("");
        txt_PasswordNuevoUsuario.setText("");
        cmb_CargoNuevoUsuario.setSelectedIndex(0);
    
    
    }
}
