package Interfaz_Login;

import Gimnasio.ConexionLocal;
import Gimnasio.ValidacionLetra;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


public class RegistrarCliente extends javax.swing.JFrame {

    String usuario,cliente;
    public static String nombreClienteNuevo= "";
    public static String apellidopaternoClienteNuevo= "";
    public static String apellidomaternoClienteNuevo= "";
    public static int IDCLIENTEPAGA=0;
    ValidacionLetra validarLetra =new ValidacionLetra();
    public RegistrarCliente() {
        initComponents();
        usuario = LogIn.user;
        setTitle("Registro de Nuevo Cliente");
        setSize(840,470);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        rsscalelabel.RSScaleLabel.setScaleLabel(lbl_FondoRegistrarCliente, "E:\\7to ciclo\\Java\\JavaApplication2\\Proyecto_Gimnasio\\src\\Imagenes\\fondo.jpg");
        this.repaint();
                

        
    }
    /*@Override*/
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_TituloRegistroCliente = new javax.swing.JLabel();
        lbl_NombreNuevoCliente = new javax.swing.JLabel();
        txt_NombreNuevoCliente = new javax.swing.JTextField();
        lbl_ApellidoPaternoNuevoCliente = new javax.swing.JLabel();
        txt_ApellidoPaternoNuevoCliente = new javax.swing.JTextField();
        lbl_ApellidoMaternoNuevoCliente = new javax.swing.JLabel();
        txt_ApellidoMaternoNuevoCliente = new javax.swing.JTextField();
        lbl_NumeroCelularNuevoCliente = new javax.swing.JLabel();
        txt_NumeroCelularNuevoCliente = new javax.swing.JTextField();
        lbl_EmailNuevoCliente = new javax.swing.JLabel();
        txt_EmailNuevoCliente = new javax.swing.JTextField();
        lbl_EdadNuevoCliente = new javax.swing.JLabel();
        txt_EdadNuevoCliente = new javax.swing.JTextField();
        lbl_SexoNuevoCliente = new javax.swing.JLabel();
        cmb_SexoNuevoCliente = new javax.swing.JComboBox<>();
        lbl_ObservacionesNuevoCliente = new javax.swing.JLabel();
        txt_ObservacionesNuevoCliente = new javax.swing.JTextField();
        btn_AceptarNuevoCliente = new javax.swing.JButton();
        btn_CancelarNuevoCliente = new javax.swing.JButton();
        lbl_FondoRegistrarCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_TituloRegistroCliente.setFont(new java.awt.Font("Leelawadee UI", 3, 24)); // NOI18N
        lbl_TituloRegistroCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_TituloRegistroCliente.setText("Registro de Cliente");
        getContentPane().add(lbl_TituloRegistroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 230, -1));

        lbl_NombreNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_NombreNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_NombreNuevoCliente.setText("Nombre:");
        getContentPane().add(lbl_NombreNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, 30));

        txt_NombreNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_NombreNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NombreNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_NombreNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NombreNuevoClienteActionPerformed(evt);
            }
        });
        txt_NombreNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_NombreNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 130, 30));

        lbl_ApellidoPaternoNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ApellidoPaternoNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_ApellidoPaternoNuevoCliente.setText("Apellido Paterno:");
        getContentPane().add(lbl_ApellidoPaternoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, 30));

        txt_ApellidoPaternoNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ApellidoPaternoNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ApellidoPaternoNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ApellidoPaternoNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoPaternoNuevoClienteActionPerformed(evt);
            }
        });
        txt_ApellidoPaternoNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoPaternoNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ApellidoPaternoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, 30));

        lbl_ApellidoMaternoNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ApellidoMaternoNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_ApellidoMaternoNuevoCliente.setText("Apellido Materno:");
        getContentPane().add(lbl_ApellidoMaternoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, -1, 30));

        txt_ApellidoMaternoNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ApellidoMaternoNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ApellidoMaternoNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ApellidoMaternoNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ApellidoMaternoNuevoClienteActionPerformed(evt);
            }
        });
        txt_ApellidoMaternoNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApellidoMaternoNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ApellidoMaternoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 130, 30));

        lbl_NumeroCelularNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_NumeroCelularNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_NumeroCelularNuevoCliente.setText("Numero de Celular:");
        getContentPane().add(lbl_NumeroCelularNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 30));

        txt_NumeroCelularNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_NumeroCelularNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NumeroCelularNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_NumeroCelularNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NumeroCelularNuevoClienteActionPerformed(evt);
            }
        });
        txt_NumeroCelularNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NumeroCelularNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_NumeroCelularNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, 30));

        lbl_EmailNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_EmailNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_EmailNuevoCliente.setText("Email:");
        getContentPane().add(lbl_EmailNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 30));

        txt_EmailNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_EmailNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_EmailNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_EmailNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailNuevoClienteActionPerformed(evt);
            }
        });
        txt_EmailNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_EmailNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_EmailNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 400, 30));

        lbl_EdadNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_EdadNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_EdadNuevoCliente.setText("Edad:");
        getContentPane().add(lbl_EdadNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, 30));

        txt_EdadNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_EdadNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_EdadNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_EdadNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EdadNuevoClienteActionPerformed(evt);
            }
        });
        txt_EdadNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_EdadNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_EdadNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 130, 30));

        lbl_SexoNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_SexoNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_SexoNuevoCliente.setText("Sexo:");
        getContentPane().add(lbl_SexoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 30));

        cmb_SexoNuevoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cmb_SexoNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_SexoNuevoClienteActionPerformed(evt);
            }
        });
        cmb_SexoNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmb_SexoNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(cmb_SexoNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 130, 30));

        lbl_ObservacionesNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_ObservacionesNuevoCliente.setForeground(new java.awt.Color(255, 102, 0));
        lbl_ObservacionesNuevoCliente.setText("Observaciones:");
        getContentPane().add(lbl_ObservacionesNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, 30));

        txt_ObservacionesNuevoCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ObservacionesNuevoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ObservacionesNuevoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ObservacionesNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ObservacionesNuevoClienteActionPerformed(evt);
            }
        });
        txt_ObservacionesNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ObservacionesNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(txt_ObservacionesNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 400, 90));

        btn_AceptarNuevoCliente.setText("Aceptar");
        btn_AceptarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarNuevoClienteActionPerformed(evt);
            }
        });
        btn_AceptarNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_AceptarNuevoClienteKeyTyped(evt);
            }
        });
        getContentPane().add(btn_AceptarNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 160, 40));

        btn_CancelarNuevoCliente.setText("Cancelar");
        btn_CancelarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarNuevoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CancelarNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 160, 40));
        getContentPane().add(lbl_FondoRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NombreNuevoClienteActionPerformed
        
    }//GEN-LAST:event_txt_NombreNuevoClienteActionPerformed

    private void txt_NombreNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreNuevoClienteKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_NombreNuevoClienteKeyTyped

    private void txt_ApellidoPaternoNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoPaternoNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoPaternoNuevoClienteActionPerformed

    private void txt_ApellidoPaternoNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoPaternoNuevoClienteKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_ApellidoPaternoNuevoClienteKeyTyped

    private void txt_ApellidoMaternoNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ApellidoMaternoNuevoClienteActionPerformed

    private void txt_ApellidoMaternoNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApellidoMaternoNuevoClienteKeyTyped
        validarLetra.soloLetras(evt);
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_ApellidoMaternoNuevoClienteKeyTyped

    private void txt_NumeroCelularNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NumeroCelularNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NumeroCelularNuevoClienteActionPerformed

    private void txt_NumeroCelularNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NumeroCelularNuevoClienteKeyTyped
        validarLetra.soloNumeros(evt);
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_NumeroCelularNuevoClienteKeyTyped

    private void txt_EmailNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailNuevoClienteActionPerformed

    private void txt_EmailNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EmailNuevoClienteKeyTyped
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_EmailNuevoClienteKeyTyped

    private void txt_EdadNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EdadNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EdadNuevoClienteActionPerformed

    private void txt_EdadNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_EdadNuevoClienteKeyTyped
        validarLetra.soloNumeros(evt);
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_EdadNuevoClienteKeyTyped

    private void cmb_SexoNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_SexoNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_SexoNuevoClienteActionPerformed

    private void cmb_SexoNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_SexoNuevoClienteKeyTyped
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_cmb_SexoNuevoClienteKeyTyped

    private void btn_AceptarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarNuevoClienteActionPerformed
        int sexo,error=0,edadInt=0;
        String nombre,apellidoPaterno,apellidoMaterno,celular,email,edad ="",cmb_sexo,observaciones;
        nombre =txt_NombreNuevoCliente.getText().trim();
        apellidoPaterno =txt_ApellidoPaternoNuevoCliente.getText().trim();
        apellidoMaterno =txt_ApellidoMaternoNuevoCliente.getText().trim();
        celular =txt_NumeroCelularNuevoCliente.getText().trim();
        email =txt_EmailNuevoCliente.getText().trim();
        edadInt=Integer.parseInt(txt_EdadNuevoCliente.getText().trim());
        observaciones =txt_ObservacionesNuevoCliente.getText().trim();
        sexo= cmb_SexoNuevoCliente.getSelectedIndex()+1;

        if(nombre.equals("")){
            txt_NombreNuevoCliente.setBackground(Color.RED);
            error++;
        }
        if(apellidoPaterno.equals("")){
            txt_ApellidoPaternoNuevoCliente.setBackground(Color.RED);
            error++;
        }
        if(apellidoMaterno.equals("")){
            txt_ApellidoMaternoNuevoCliente.setBackground(Color.RED);
            error++;
        }
        if(celular.equals("")){
            txt_NumeroCelularNuevoCliente.setBackground(Color.RED);
            error++;
        }
        if(edadInt<=0 || edadInt >=70 ){
            txt_EdadNuevoCliente.setBackground(Color.RED);
            JOptionPane.showMessageDialog(null,"La edad no puede ser más de 70 años\n Rellene otra vez el campo");
            txt_EdadNuevoCliente.setText("");           
            error++;
        }
        else
            edad= Integer.toString(edadInt);
        
        if(edad.equals("")){
            txt_EdadNuevoCliente.setBackground(Color.RED);
            error++;
        }
        if (sexo==1) {
            cmb_sexo="Masculino";
        } else {
            cmb_sexo="Femenino";
        }

        try {
            Connection cn = ConexionLocal.Conexion();

            PreparedStatement pst = cn.prepareStatement("select cli_nombre from tbl_Cliente where cli_nombre = '"+nombre+"' and cli_ApellidoPaterno = '"+ apellidoPaterno + "' and cli_ApellidoMaterno = '"+ apellidoMaterno + "' ");

            ResultSet rs = pst.executeQuery();
            
            
            if (rs.next()) {
                txt_NombreNuevoCliente.setBackground(Color.red);
                txt_ApellidoPaternoNuevoCliente.setBackground(Color.red);
                txt_ApellidoMaternoNuevoCliente.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Cliente ya registrado ");
                txt_NombreNuevoCliente.setText("");
                txt_ApellidoPaternoNuevoCliente.setText("");
                txt_ApellidoMaternoNuevoCliente.setText("");
                cn.close();
            } else {

                cn.close();
                if (error == 0) {
                    try {
                        try (Connection cn2 = ConexionLocal.Conexion()) {
                            PreparedStatement pst2 = cn2.prepareStatement
                            ("INSERT INTO tbl_Cliente  VALUES (?,?,?,?,?,?,?,?,?)");

                            pst2.setInt(1, 0);
                            pst2.setString(2, nombre);
                            pst2.setString(3, apellidoPaterno);
                            pst2.setString(4, apellidoMaterno);
                            pst2.setString(5, edad);
                            pst2.setString(6, cmb_sexo);
                            pst2.setString(7, celular);
                            pst2.setString(8, email);
                            pst2.setString(9, observaciones);

                            pst2.executeUpdate();
                            nombreClienteNuevo=nombre;
                            apellidopaternoClienteNuevo= apellidoPaterno;
                            apellidomaternoClienteNuevo=apellidoMaterno;
                            //try
                            
                        }
                        CamposVacios();
                        //JOptionPane.showMessageDialog(null,"Registro Exitoso");
                        //this.dispose();
                        RegistrarPaga registrarPaga = new RegistrarPaga();
                        registrarPaga.setVisible(true);

                    } catch (SQLException e) {
                        System.err.println("No se pudo registrar al cliente"+ e);
                        JOptionPane.showMessageDialog(null,"Error al agregar cliente");
                        CamposVacios();

                    }
                } else {
                    JOptionPane.showMessageDialog(null,"Rellene todos los campos obligatorios");

                }

            }
        } catch (SQLException e) {
            System.err.println("No se puedo validar el nombre de cliente");
            JOptionPane.showMessageDialog(null,"Error en la Base de Datos"+ e);
        }

    }//GEN-LAST:event_btn_AceptarNuevoClienteActionPerformed

    private void btn_AceptarNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_AceptarNuevoClienteKeyTyped
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_btn_AceptarNuevoClienteKeyTyped

    private void txt_ObservacionesNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ObservacionesNuevoClienteKeyTyped
        char tecEnter= evt.getKeyChar();

        if(tecEnter==KeyEvent.VK_ENTER){
            btn_AceptarNuevoCliente.doClick();

        }
    }//GEN-LAST:event_txt_ObservacionesNuevoClienteKeyTyped

    private void txt_ObservacionesNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ObservacionesNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ObservacionesNuevoClienteActionPerformed

    private void btn_CancelarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarNuevoClienteActionPerformed
        CamposVacios();
        dispose();
    }//GEN-LAST:event_btn_CancelarNuevoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AceptarNuevoCliente;
    private javax.swing.JButton btn_CancelarNuevoCliente;
    private javax.swing.JComboBox<String> cmb_SexoNuevoCliente;
    private javax.swing.JLabel lbl_ApellidoMaternoNuevoCliente;
    private javax.swing.JLabel lbl_ApellidoPaternoNuevoCliente;
    private javax.swing.JLabel lbl_EdadNuevoCliente;
    private javax.swing.JLabel lbl_EmailNuevoCliente;
    private javax.swing.JLabel lbl_FondoRegistrarCliente;
    private javax.swing.JLabel lbl_NombreNuevoCliente;
    private javax.swing.JLabel lbl_NumeroCelularNuevoCliente;
    private javax.swing.JLabel lbl_ObservacionesNuevoCliente;
    private javax.swing.JLabel lbl_SexoNuevoCliente;
    private javax.swing.JLabel lbl_TituloRegistroCliente;
    private javax.swing.JTextField txt_ApellidoMaternoNuevoCliente;
    private javax.swing.JTextField txt_ApellidoPaternoNuevoCliente;
    private javax.swing.JTextField txt_EdadNuevoCliente;
    private javax.swing.JTextField txt_EmailNuevoCliente;
    private javax.swing.JTextField txt_NombreNuevoCliente;
    private javax.swing.JTextField txt_NumeroCelularNuevoCliente;
    private javax.swing.JTextField txt_ObservacionesNuevoCliente;
    // End of variables declaration//GEN-END:variables
    public void CamposVacios(){
        txt_NombreNuevoCliente.setText("");
        txt_ApellidoPaternoNuevoCliente.setText("");
        txt_ApellidoMaternoNuevoCliente.setText("");
        txt_EdadNuevoCliente.setText("");
        txt_NumeroCelularNuevoCliente.setText("");
        txt_EmailNuevoCliente.setText("");
        txt_ObservacionesNuevoCliente.setText("");
        cmb_SexoNuevoCliente.setSelectedIndex(0);
    
    }
}
